### ISSUE TITLE
Add setting to disable hiding the youtube comments

### ISSUE THREAD

**Issue by marcusabu** [odensc/karamel#10]
Love the extension!,
However by default, the youtube comments are hidden when there are reddit comments to be shown. Personally, I'd prefer for youtube comments to always be shown under the reddit comments. Especially when there are very little (or no) reddit comments under the post it just takes an extra step to see comments.

Thanks!

**Comment by odensc** [comment]
Thanks for the suggestion. I've added that option in `v1.4.0`. It should show up in the Chrome store soon.
