### ISSUE TITLE
Firefox extension?

### ISSUE THREAD

**Issue by Tank-Missile** [odensc/karamel#16]
How hard would it be to start making releases for Firefox?

**Comment by odensc** [comment]
I tried a while back but ran into some weird issues. I'll try again soon.

**Comment by achugb** [comment]
Would love to see this. Karamel is quite polished

**Comment by imzondax** [comment]
> I tried a while back but ran into some weird issues. I'll try again soon.

How is this coming a long, or is firefox side of the project put to the side for the moment?

**Comment by odensc** [comment]
@imzondax I can probably only do it once I rewrite the extension - a lot of it is tied to Chrome-specific APIs. I wanted to do this anyways so I can implement new features easier, but not sure on the timeline of it.

**Comment by odensc** [comment]
I've submitted a Firefox version for approval. It should live here if/when approved: https://addons.mozilla.org/en-US/developers/addon/karamel

In the meantime, here's a zip file of v2.0.0 for Firefox: [karamel-firefox-2.0.0.zip](https://github.com/user-attachments/files/17007232/karamel-firefox-2.0.0.zip)

You can load this by unzipping it, navigating to the URL `about:debugging` > click "This Firefox" tab on the left-hand side > Load Temporary Add-on > Navigate to unzipped folder > Select "manifest.json" file > Open.

**Comment by achugb** [comment]
Gave this a try. I think the min version might need to be updated to that
of firefox's?

**Comment by achugb** [comment]
115. I think something may be bugged with my ff install since it thinks
that's the latest version. Sorry for the confusion

**Comment by achugb** [comment]
Ah. I have the extended support release
