### ISSUE TITLE
Causes dropped frames

### ISSUE THREAD

**Issue by pearlythepirate** [odensc/karamel#25]
After isolating the issue to this extension, I find it was causing a significant and noticeable number of dropped frames whenever loaded.

If you need data, please let me know how I can help.

Windows 10, latest Chrome version.

**Comment by odensc** [comment]
So with no other extensions other than this one installed, you get dropped frames? And when disabling the extension, the issue disappears?

No idea what would cause that... the only thing this extension does in the background is check for URL changes every 1s, but that shouldn't really have a performance impact at all.

Are you getting consistent dropped frames or they come in clusters?

**Comment by pearlythepirate** [comment]
I apologize, I did a bit of more extensive testing and can't seem to reproduce it. My first whack was to disable SponsorBlock, Enhancer for YouTube, and this extension and reenable one at a time. I also tried on a fresh Chrome profile with just this extension and no issues. Sorry for the inconvenience!
