### ISSUE TITLE
Show reddit comments when youtube video has comments disabled

### ISSUE THREAD

**Issue by bas-mols** [odensc/karamel#32]
The extension currently does not work when the youtube comments are disabled
![image](https://user-images.githubusercontent.com/84536844/119025605-975a8880-b9a4-11eb-9d4b-7cc62c23619c.png)

**Comment by LetrixZ** [comment]
It does for me:

![image](https://user-images.githubusercontent.com/25001812/165343436-92044270-82a4-4c83-97c2-c12f2a6b0f9d.png)

**Comment by odensc** [comment]
This should be fixed with #36 once published to the Chrome Web Store.
