### ISSUE TITLE
Comments not loading

### ISSUE THREAD

**Issue by baconpie** [odensc/karamel#38]
Reddit thread will load, and tell you how many comments there are, but the comments will never load. Just shows spinning loading icon forever.

**Comment by brussell98** [comment]
Seems like the API route used to get comments that the extension uses was removed. It's now under `/comments`.
I made the following change (and after much effort built a 7-year old webpack project) and it's working again:

```diff
 export function getPost(postId: string, sort: string) {
-       return ajax({ url: `/${postId}.json?sort=${sort}`, method: "GET" }).pipe(
+       return ajax({ url: `/comments/${postId}.json?sort=${sort}`, method: "GET" }).pipe(
                map(res => res)
        );
 }
```

**Comment by QuantumManiac** [comment]
> Seems like the API route that the extension uses to get comments was moved. It's now under `/comments`. I made the following change (and after much effort built a 7-year old webpack project) and it's working again:
> 
> ```diff
>  export function getPost(postId: string, sort: string) {
> -       return ajax({ url: `/${postId}.json?sort=${sort}`, method: "GET" }).pipe(
> +       return ajax({ url: `/comments/${postId}.json?sort=${sort}`, method: "GET" }).pipe(
>                 map(res => res)
>         );
>  }
> ```

Worked for me, thanks for the fix! Not too much webpack-wrangling required on my side. I managed to get the extension built using node v8.17.0 and a fresh `npm install`

**Comment by odensc** [comment]
Thanks all, I'm just now getting some time this weekend to look at it. To get it published to the Chrome store, it might take a bit longer because I need to update to manifest v3 and not sure how much of a lift that will be.

**Comment by odensc** [comment]
The manifest v3 update was easier than expected. I've uploaded v2.0.0 to the Chrome Web Store for review.
