### ISSUE TITLE
Not working at all for me

### ISSUE THREAD

**Issue by sprite-1** [odensc/karamel#5]
Do I need to do anything extra for this to work? I'm on Linux with the latest Chrome installed.

**Comment by odensc** [comment]
Hi @sprite-1, thanks for filing an issue. I use Chrome on Linux as well so hopefully we can figure this out.

1. Can you confirm that visiting a video (like this one: https://www.youtube.com/watch?v=5PRDtYHlajA) that 100% has a reddit thread still doesn't show anything? 
2. What Chrome version are you using?
3. Does the button to switch Reddit/YT comments show up on the page?

Also, if you could check the Network tab in devtools to see if any requests to `reddit` are being sent  and take a screenshot of it, that would be great.

**Comment by sprite-1** [comment]
This is what happens when I load a video, it loads the YouTube comments by default despite it being set to Reddit. And yeah, the button does show up, clicking on it just changes the icon to Reddit but nothing else.
![image](https://user-images.githubusercontent.com/33685433/52846340-4e238a80-3144-11e9-87a5-0ce94fd22d29.png)

Chrome version is 
![image](https://user-images.githubusercontent.com/33685433/52846386-6dbab300-3144-11e9-838b-d34e1fa40765.png)

This is the Network tab screenshot I filtered for anything "reddit" but nothing showed up.
![image](https://user-images.githubusercontent.com/33685433/52846566-e6ba0a80-3144-11e9-87e0-aa6d941f2f6f.png)

**Comment by odensc** [comment]
Hmm, this is weird. I just tried on a fresh install of Chrome with only this extension and it works. Perhaps you have another extension conflicting with it. Can you try making a new profile with only Karamel installed and see if it works?

**Comment by sprite-1** [comment]
Hi, I just tried on a new profile and it says "No comments found" for that particular video you linked prior. Same thing on my main profile. Before, it showed a clickable button but now it also just says "No comments found"

**Comment by odensc** [comment]
Hi @sprite-1, so sorry for the late response, I haven't had much time to deal with this. After looking into it, I've determined it's because of an update in Chrome 73 that [blocked cross-origin requests in content scripts.](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches) I'll have to convert from pure XHR requests to a background script messaging system, so I'm going to fix this ASAP.

**Comment by sprite-1** [comment]
Hey no worries man, take your time! 👍

**Comment by odensc** [comment]
I've fixed this in the latest version (v1.3.0) which should be automatically updated in the next few hours. Thanks for the bug report!
